/************************************************/
/**** CETTE CLASSE NE DOIT PAS ÊTRE MODIFIÉE ****/
/************************************************/
package presentation;

import domaine.Employe;
import metier.ListeFonctions;
import java.awt.Component;

/**
 * 634.1-Programmation / TP P05
 * 
 * Fenêtre de saisie d'un nouvel employé - Singleton
 *
 * @author Peter DAEHNE - HEG-Genève
 * @version 1.0
*/
public class FrmNouveau extends java.awt.Frame {
  
  private static FrmNouveau uniqueInstance = null; /* L'unique instance */
  private FrmMain frmMain;                         /* La référence à la fenêtre principale */
  
  private ListeFonctions listeFonctions; /* Modèle */

  /** Constructeur */
  private FrmNouveau () {
    initComponents();
    chargerFonctions();
    btnEnregistrer.setEnabled(false);
  } // Constructeur
  
  /** Retourne l'unique instance */
  public static FrmNouveau getInstance (FrmMain frmMain) {
    if (uniqueInstance == null) {uniqueInstance = new FrmNouveau(); uniqueInstance.frmMain = frmMain;}
    return uniqueInstance;
  } // getInstance
  
  /* Chargement des fonctions dans l'ordre des libellés et sélection de la première */
  private void chargerFonctions () {
    listeFonctions = new ListeFonctions();
    for (int k = 0; k < listeFonctions.size(); k++) {lstFonctions.add(listeFonctions.get(k).toString());}
    listeFonctions.setPos(0); lstFonctions.select(0);
  } // chargerFonctions

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
  */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        tfNom = new java.awt.TextField();
        label2 = new java.awt.Label();
        tfPrenom = new java.awt.TextField();
        label3 = new java.awt.Label();
        tfBureau = new java.awt.TextField();
        label4 = new java.awt.Label();
        lstFonctions = new java.awt.List();
        btnEnregistrer = new java.awt.Button();

        setFocusTraversalPolicy(new MyFocusTraversalPolicy(new Component[]{tfNom,tfPrenom,tfBureau,lstFonctions,btnEnregistrer}));
        setResizable(false);
        setTitle("Saisie d'un employé");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setText("Nom");

        tfNom.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfTextValueChanged(evt);
            }
        });

        label2.setText("Prénom");

        tfPrenom.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfTextValueChanged(evt);
            }
        });

        label3.setText("Bureau");

        tfBureau.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfTextValueChanged(evt);
            }
        });

        label4.setText("Fonction");

        lstFonctions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstFonctionsItemStateChanged(evt);
            }
        });
        lstFonctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstFonctionsActionPerformed(evt);
            }
        });

        btnEnregistrer.setLabel("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBureau, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstFonctions, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(tfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnregistrer.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /* Fin de l'application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    dispose();
  }//GEN-LAST:event_exitForm

  /* L'un des trois champs de saisie (tfNom, tfPrenom, tfBureau) a changé de valeur */
  private void tfTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tfTextValueChanged
    btnEnregistrer.setEnabled(tfNom.getText().trim().length() != 0 && tfPrenom.getText().trim().length() != 0 && tfBureau.getText().trim().length() != 0);
  }//GEN-LAST:event_tfTextValueChanged

  /* Le bouton btnEnregistrer a été appuyé */
  private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
    frmMain.addEmploye(new Employe(tfNom.getText().trim(), tfPrenom.getText().trim(), listeFonctions.getCourant(), tfBureau.getText().trim()));
    tfNom.setText(""); tfPrenom.setText(""); tfBureau.setText("");
  }//GEN-LAST:event_btnEnregistrerActionPerformed

  /* La sélection dans la liste des fonctions a changé */
  private void lstFonctionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstFonctionsItemStateChanged
    listeFonctions.setPos(lstFonctions.getSelectedIndex());
  }//GEN-LAST:event_lstFonctionsItemStateChanged

    private void lstFonctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstFonctionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstFonctionsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnregistrer;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.List lstFonctions;
    private java.awt.TextField tfBureau;
    private java.awt.TextField tfNom;
    private java.awt.TextField tfPrenom;
    // End of variables declaration//GEN-END:variables

} // FrmNouveau